timeout: 120s
steps:
    - name: gcr.io/cloud-builders/npm:current
      args:
          - install
    - name: gcr.io/cloud-builders/npm:current
      args:
          - run
          - build
    - name: gcr.io/cloud-builders/npm:current
      entrypoint: 'apt-get'
      args:
          - install
          - libssl1.0.0
          - libssl-dev
          - --reinstall
    - name: gcr.io/cloud-builders/npm:current
      entrypoint: 'ln'
      args:
          - -s
          - /lib/x86_64-linux-gnu/libssl.so.1.0.0
          - /usr/lib/libssl.so.10
    - name: gcr.io/cloud-builders/npm:current
      entrypoint: 'ln'
      args:
          - -s
          - /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
          - /usr/lib/libcrypto.so.10


      entrypoint: 'ln'
      args:
          - -s
          - libcrypto.so.1.1
          - libcrypto.so
      entrypoint: 'ln'
      args:
          - -s
          - libssl.so.1.1
          - libssl.so
    
    - name: gcr.io/cloud-builders/npm:current
      entrypoint: 'bash'
      args:
          - export
          - LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64

    - name: gcr.io/cloud-builders/npm:current
      entrypoint: 'ldconfig'
    - name: gcr.io/cloud-builders/npm:current
      args:
          - run
          - test
      env:
          - MONGOMS_DOWNLOAD_URL=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-4.2.8.tgz
    - name: 'ubuntu'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              echo //registry.npmjs.org/:_authToken=${_NPM_TOKEN} > .npmrc ;
              echo email=devops@expan.do >> .npmrc ;
              echo always-auth=true >> .npmrc ;
              cat .npmrc ;
      volumes:
          - name: 'home'
            path: /root/
    - name: 'gcr.io/cloud-builders/npm'
      args: ['publish']
      env:
          - HOME=/root/
      volumes:
          - name: 'home'
            path: /root/
